version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    # Trigger an immediate Dependabot re-check after publishing a new upstream tag.
    schedule:
      interval: daily
    labels:
      - automerge
